# Your E621 username
login: MyUsername 

# Your API key, see https://e621.net/help/api
api_key: a1b2c3d4e5f6g7h8

# A custom user agent
user_agent: MyProject/1.0 (by MyUsername on e621)

# Cache directory
cache_dir: .e621cache

# Maximum number of requests to send per second
max_requests_per_second: 2
